### ISSUE TITLE
`dataset_timestamp` when set causes an exception

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs#259] opened 2021-07-16 00:14 UTC
### Summary

From an user 
```
fyi - if with_rotation_time is not set (None) and dataset_timestamp is set - it causes an exception in the whylogs library
AttributeError: 'int' object has no attribute 'replace'
    dataset_timestamp = time.to_utc_ms(profile.dataset_timestamp).__str__()
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/util/time.py", line 19, in to_utc_ms
    kwargs = self.template_params(profile)
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 150, in template_params
    self._write_json(profile, rotation_suffix)    dataset_timestamp = time.to_utc_ms(profile.dataset_timestamp).__str__()
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/util/time.py", line 19, in to_utc_ms
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 199, in _write_json
    path = self.ensure_path(os.path.join(self.path_suffix(profile), "json"))
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 106, in path_suffix
kwargs = self.template_params(profile)
    dataset_timestamp = time.to_utc_ms(profile.dataset_timestamp).__str__()
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/util/time.py", line 19, in to_utc_ms
    kwargs = self.template_params(profile)
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 150, in template_params
    path = self.ensure_path(os.path.join(self.path_suffix(profile), "json"))
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 106, in path_suffix
    path = self.ensure_path(os.path.join(self.path_suffix(profile), "json"))
  File "/home/dtkachov/Documents/Programs/python/.venv/lib/python3.8/site-packages/whylogs/app/writers.py", line 106, in path_suffix
    kwargs = self.template_params(profile)
    return int(dt.replace(tzinfo=datetime.timezone.utc).timestamp() * 1000.0)

```

**Comment by lalmei** [comment] 2021-07-19 20:07
@andyndang , Couldn't reproduce this bug, however note that currently `dataset_timestamp` expects a `datetime.datetime` object, not an `int`.  I do feel it is a bit confusing since in most languages a timestamp is a int64. Closing it for now, until we get more clarification.

**Closed as completed by lalmei** 2021-07-19 20:07 UTC
Labels: bug
