### ISSUE TITLE
Logger profiles are empty when logging with segments

### ISSUE THREAD

**Issue by msharp-shop** [whylabs/whylogs#965] opened 2022-11-09 22:08 UTC
## Description

Profiles are empty when using a logger and supplying a DatasetSchema with segments.  This is using version 1.1.11 that just came out today.

- System info
  - Operating system and version: macOS 13.0
  - Browser and version: n/a
- Steps to reproduce:
  - You can run the following script:
  
```python
import os
import time
import pandas as pd
import whylogs as why
from sklearn.datasets import load_iris

from whylogs.core.schema import DatasetSchema
from whylogs.core.segmentation_partition import segment_on_column

print("Setting up")
tmp_path = "logs"
if not os.path.isdir(tmp_path):
    os.makedirs(tmp_path)

why_logger = why.logger(
    mode="rolling", interval=5, when="S", base_name="segmentation_fault"
)
why_logger.append_writer("local", base_dir=tmp_path)

iris = load_iris(as_frame=True).frame

print("Running logger")
for i in range(30):
    why_logger.log(iris.sample(), schema=DatasetSchema(segments=segment_on_column("target")))
    time.sleep(1)

why_logger.close()

print("Print profiles - unexpected empty results:")
all_files = [f for f in os.listdir(tmp_path) if not f.startswith('.')]
for file in all_files:
    path = os.path.join(tmp_path, file)
    view = why.read(path).view()
    print(view.to_pandas().head())
    
print("Regular log works")
results = why.log(iris.sample(), schema=DatasetSchema(segments=segment_on_column("target")))
print(results)
view = results.profile(results.segments()[0]).view()
print(view.to_pandas().head())  
```

<img width="746" alt="image" src="https://user-images.githubusercontent.com/110247659/200948653-8a51270d-0ecc-482f-9f68-daed3ed5f9e3.png">

## Suggestions

Expect `logger.log()` to work the same as `why.log()`

## Related

Relates to organization/repo#number 

- [ ] I have reviewed the [Guidelines for Contributing](https://github.com/whylabs/whylogs/blob/mainline/.github/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/whylabs/whylogs/blob/mainline/.github/CODE_OF_CONDUCT.md).

**Comment by jamie256** [comment] 2022-11-10 02:16
Appears to be same underlying root cause, segmented profiles get serialized with the whylabs and local writer as v0 format which can't be read back with why.read which expects v1 file format. Candidate fix in dev release: https://pypi.org/project/whylogs/1.1.12.dev0

**Comment by jamie256** [comment] 2022-11-15 17:24
fixed by https://github.com/whylabs/whylogs/pull/971

**Comment by jamie256** [comment] 2022-11-17 17:14
fixed in release https://github.com/whylabs/whylogs/releases/tag/v1.1.13

**Closed as completed by jamie256** 2022-11-17 17:14 UTC
Labels: bug
