### ISSUE TITLE
DatasetProfile.track cannot handle `None` data

### ISSUE THREAD

**Issue by ibackus** [whylabs/whylogs#111] opened 2020-12-18 23:26 UTC
I encountered this when processing a dataframe with values equal to `None`.  A datasetprofile cannot be generated for data that has `None` values when running `track_dataframe`.

Probably we an have separate methods for tracking an individual value versus a dictionary of values.

```python
from whylogs import DatasetProfile
p = DatasetProfile('name')
p.track('column name', None)


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-52-9c0f4562f8ba> in <module>
      1 from whylogs import DatasetProfile
      2 p = DatasetProfile('name')
----> 3 p.track('column name', None)

~/miniconda3/envs/data/lib/python3.8/site-packages/whylogs/core/datasetprofile.py in track(self, columns, data)
    182             self.track_datum(columns, data)
    183         else:
--> 184             for column_name, data in columns.items():
    185                 self.track_datum(column_name, data)
    186 

AttributeError: 'str' object has no attribute 'items'
```

**Comment by andyndang** [comment] 2020-12-18 23:27
This is duplicate of #89 FYI

**Comment by ibackus** [comment] 2020-12-18 23:28
lol.  Should have searched for my own issues :)

**Closed as completed by andyndang** 2020-12-18 23:27 UTC
